### ISSUE TITLE
Moshi IllegalArgumentException

### ISSUE THREAD

**Issue by jaydipumaretiya** [pink-room/walletconnectkit-android#10]
When I implement your code try to run I got this issue, 

java.lang.IllegalArgumentException: Cannot serialize Kotlin type org.walletconnect.impls.MoshiPayloadAdapter$EncryptedPayload. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.

**Comment by bffcorreia** [comment]
Hi @jaydipumaretiya. Do you have any code sample showcasing the error? We are using `KotlinJsonAdapterFactory` and the provided sample in the repo is working fine.

**Comment by jaydipumaretiya** [comment]
Hello, @bffcorreia, I found the issue where I'm doing mistakes. 
If We are using the `minifyEnabled true` in Gradle at that time I face this issue I think need to add some ProGuard rules in it. 

I have another question If I want to do a transfer from TRX or Any other coin then What do I need to do? 
Can you please guide us?

**Comment by jaydipumaretiya** [comment]
Solved by changing `minifyEnabled true` to `false`. But you need to write some ProGuard rules for `minifyEnabled true`

**Comment by RyanNewsom** [comment]
This should be re-opened... Y'all should really include proguard rules in your lib and documentation

**Comment by RyanNewsom** [comment]
@bffcorreia  ^

**Comment by sinarostami** [comment]
Add below lines into progaurd-ruls.pro file:
```
-keep class org.walletconnect** { *;}
-keep class dev.pinkroom.walletconnectkit** { *; }
```

**Comment by sinarostami** [comment]
Add below lines into the progaurd-rules.pro file:

```
-keep class org.walletconnect** { *;}
-keep class dev.pinkroom.walletconnectkit** { *; }
```
